name: CI

on:
  push:
    branches:
      - '*'

jobs:
  buildtest:
    name: Test Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install Packages
      run: sudo apt install -y cmake check libbsd-dev libglib2.0-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug

